export const LOGGED_USER_DETAILS= 'LOGGED_USER_DETAILS';
export const LOGIN_REQUESTING='LOGIN_REQUESTING';

export const LOAD_ALL_USERS= 'LOAD_ALL_USERS';
export const LOAD_ALL_USERS_SUCCESS = 'LOAD_ALL_USERS_SUCCESS';
